### ISSUE TITLE
Problem with mainland-pretty-0.4.0.0

### ISSUE THREAD

**Issue by alogic0** [feuerbach/prover#2]
In the latest [mainland-pretty-0.4.0.0](https://hackage.haskell.org/package/mainland-pretty-0.4.0.0/docs/Text-PrettyPrint-Mainland.html) the `Doc` isn't instance of `Show`, so compilation of Ast.hs gives an error:

``` code
src\Ast.hs:46:10:
    No instance for (Show Doc) arising from a use of `show'
    In the first argument of `(.)', namely `show'
    In the expression: show . ppr
    In an equation for `show': show = show . ppr
```

**Comment by UnkindPartition** [comment]
You should use provided stack.yaml. It specifies the correct package versions. Just run `stack install` inside the directory.

**Comment by alogic0** [comment]
Maybe it's worth a mention in the `Readme`. Now there is only said about `cabal install`.

By the way, manualy installing `mainland-pretty-0.2.7.2` and dirty patching `0.4.0.0` worked for me too.
